name: Automatically submit the COVID-19 report sheet of ygsoft

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Cypress run 执行脚本
        uses: cypress-io/github-action@v2

